# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BaseResizeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_baseResizeDialog(object):
    def setupUi(self, baseResizeDialog):
        baseResizeDialog.setObjectName("baseResizeDialog")
        baseResizeDialog.resize(174, 131)
        self.gridLayout = QtWidgets.QGridLayout(baseResizeDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(baseResizeDialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(baseResizeDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.dialogBtnBox = QtWidgets.QDialogButtonBox(baseResizeDialog)
        self.dialogBtnBox.setOrientation(QtCore.Qt.Horizontal)
        self.dialogBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.dialogBtnBox.setObjectName("dialogBtnBox")
        self.gridLayout.addWidget(self.dialogBtnBox, 2, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(baseResizeDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(baseResizeDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.spinBoxHeight = QtWidgets.QSpinBox(baseResizeDialog)
        self.spinBoxHeight.setMaximum(3000)
        self.spinBoxHeight.setProperty("value", 400)
        self.spinBoxHeight.setObjectName("spinBoxHeight")
        self.gridLayout.addWidget(self.spinBoxHeight, 1, 1, 1, 1)
        self.spinBoxWidth = QtWidgets.QSpinBox(baseResizeDialog)
        self.spinBoxWidth.setMaximum(4000)
        self.spinBoxWidth.setProperty("value", 600)
        self.spinBoxWidth.setObjectName("spinBoxWidth")
        self.gridLayout.addWidget(self.spinBoxWidth, 0, 1, 1, 1)

        self.retranslateUi(baseResizeDialog)
        self.dialogBtnBox.accepted.connect(baseResizeDialog.accept) # type: ignore
        self.dialogBtnBox.rejected.connect(baseResizeDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(baseResizeDialog)

    def retranslateUi(self, baseResizeDialog):
        _translate = QtCore.QCoreApplication.translate
        baseResizeDialog.setWindowTitle(_translate("baseResizeDialog", "缩放"))
        self.label.setText(_translate("baseResizeDialog", "宽度"))
        self.label_3.setText(_translate("baseResizeDialog", "高度"))
        self.label_2.setText(_translate("baseResizeDialog", " px"))
        self.label_4.setText(_translate("baseResizeDialog", " px"))
