# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BaseNewDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_baseNewDialog(object):
    def setupUi(self, baseNewDialog):
        baseNewDialog.setObjectName("baseNewDialog")
        baseNewDialog.resize(174, 131)
        self.gridLayout = QtWidgets.QGridLayout(baseNewDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(baseNewDialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(baseNewDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(baseNewDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 3)
        self.label_2 = QtWidgets.QLabel(baseNewDialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(baseNewDialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.spinBoxHeight = QtWidgets.QSpinBox(baseNewDialog)
        self.spinBoxHeight.setMaximum(3000)
        self.spinBoxHeight.setProperty("value", 400)
        self.spinBoxHeight.setObjectName("spinBoxHeight")
        self.gridLayout.addWidget(self.spinBoxHeight, 1, 1, 1, 1)
        self.spinBoxWidth = QtWidgets.QSpinBox(baseNewDialog)
        self.spinBoxWidth.setMaximum(4000)
        self.spinBoxWidth.setProperty("value", 600)
        self.spinBoxWidth.setObjectName("spinBoxWidth")
        self.gridLayout.addWidget(self.spinBoxWidth, 0, 1, 1, 1)

        self.retranslateUi(baseNewDialog)
        self.buttonBox.accepted.connect(baseNewDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(baseNewDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(baseNewDialog)

    def retranslateUi(self, baseNewDialog):
        _translate = QtCore.QCoreApplication.translate
        baseNewDialog.setWindowTitle(_translate("baseNewDialog", "新建"))
        self.label.setText(_translate("baseNewDialog", "宽度"))
        self.label_3.setText(_translate("baseNewDialog", "高度"))
        self.label_2.setText(_translate("baseNewDialog", " px"))
        self.label_4.setText(_translate("baseNewDialog", " px"))
