# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BaseRotateDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_baseRotateDialog(object):
    def setupUi(self, baseRotateDialog):
        baseRotateDialog.setObjectName("baseRotateDialog")
        baseRotateDialog.resize(210, 92)
        self.gridLayout = QtWidgets.QGridLayout(baseRotateDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.rotateClockWiseBtn = QtWidgets.QPushButton(baseRotateDialog)
        self.rotateClockWiseBtn.setObjectName("rotateClockWiseBtn")
        self.gridLayout.addWidget(self.rotateClockWiseBtn, 0, 0, 1, 1)
        self.rotateVerFlipBtn = QtWidgets.QPushButton(baseRotateDialog)
        self.rotateVerFlipBtn.setObjectName("rotateVerFlipBtn")
        self.gridLayout.addWidget(self.rotateVerFlipBtn, 0, 1, 1, 1)
        self.rotateAntiClockWiseBtn = QtWidgets.QPushButton(baseRotateDialog)
        self.rotateAntiClockWiseBtn.setObjectName("rotateAntiClockWiseBtn")
        self.gridLayout.addWidget(self.rotateAntiClockWiseBtn, 1, 0, 1, 1)
        self.rotateHorFlipBtn = QtWidgets.QPushButton(baseRotateDialog)
        self.rotateHorFlipBtn.setObjectName("rotateHorFlipBtn")
        self.gridLayout.addWidget(self.rotateHorFlipBtn, 1, 1, 1, 1)

        self.retranslateUi(baseRotateDialog)
        QtCore.QMetaObject.connectSlotsByName(baseRotateDialog)

    def retranslateUi(self, baseRotateDialog):
        _translate = QtCore.QCoreApplication.translate
        baseRotateDialog.setWindowTitle(_translate("baseRotateDialog", "旋转翻转"))
        self.rotateClockWiseBtn.setText(_translate("baseRotateDialog", "顺时针旋转"))
        self.rotateVerFlipBtn.setText(_translate("baseRotateDialog", "垂直翻转"))
        self.rotateAntiClockWiseBtn.setText(_translate("baseRotateDialog", "逆时针旋转"))
        self.rotateHorFlipBtn.setText(_translate("baseRotateDialog", "水平翻转"))
