# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BaseCropDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_baseCropDialog(object):
    def setupUi(self, baseCropDialog):
        baseCropDialog.setObjectName("baseCropDialog")
        baseCropDialog.resize(174, 131)
        self.gridLayout = QtWidgets.QGridLayout(baseCropDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(baseCropDialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(baseCropDialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.dialogBtnBox = QtWidgets.QDialogButtonBox(baseCropDialog)
        self.dialogBtnBox.setOrientation(QtCore.Qt.Horizontal)
        self.dialogBtnBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.dialogBtnBox.setObjectName("dialogBtnBox")
        self.gridLayout.addWidget(self.dialogBtnBox, 2, 0, 1, 3)
        self.spinBoxX2 = QtWidgets.QSpinBox(baseCropDialog)
        self.spinBoxX2.setMinimum(-4000)
        self.spinBoxX2.setMaximum(4000)
        self.spinBoxX2.setProperty("value", 600)
        self.spinBoxX2.setObjectName("spinBoxX2")
        self.gridLayout.addWidget(self.spinBoxX2, 1, 1, 1, 1)
        self.spinBoxX1 = QtWidgets.QSpinBox(baseCropDialog)
        self.spinBoxX1.setMinimum(-4000)
        self.spinBoxX1.setMaximum(4000)
        self.spinBoxX1.setProperty("value", 0)
        self.spinBoxX1.setObjectName("spinBoxX1")
        self.gridLayout.addWidget(self.spinBoxX1, 0, 1, 1, 1)
        self.spinBoxY1 = QtWidgets.QSpinBox(baseCropDialog)
        self.spinBoxY1.setMinimum(-3000)
        self.spinBoxY1.setMaximum(3000)
        self.spinBoxY1.setObjectName("spinBoxY1")
        self.gridLayout.addWidget(self.spinBoxY1, 0, 2, 1, 1)
        self.spinBoxY2 = QtWidgets.QSpinBox(baseCropDialog)
        self.spinBoxY2.setMinimum(-3000)
        self.spinBoxY2.setMaximum(3000)
        self.spinBoxY2.setProperty("value", 400)
        self.spinBoxY2.setObjectName("spinBoxY2")
        self.gridLayout.addWidget(self.spinBoxY2, 1, 2, 1, 1)

        self.retranslateUi(baseCropDialog)
        self.dialogBtnBox.accepted.connect(baseCropDialog.accept) # type: ignore
        self.dialogBtnBox.rejected.connect(baseCropDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(baseCropDialog)

    def retranslateUi(self, baseCropDialog):
        _translate = QtCore.QCoreApplication.translate
        baseCropDialog.setWindowTitle(_translate("baseCropDialog", "裁剪"))
        self.label.setText(_translate("baseCropDialog", "左上角"))
        self.label_3.setText(_translate("baseCropDialog", "右下角"))
